name: Setup pnpm and install cache
description: Install pnpm, Node, workspace dependencies, and Playwright browsers
runs:
  using: composite
  steps:
  - uses: pnpm/action-setup@v6
  - name: Setup node to enable caching
    uses: actions/setup-node@v7
    with:
      node-version: 26
      cache: 'pnpm'
      cache-dependency-path: './pnpm-lock.yaml'
  - name: Install dependencies
    shell: bash
    run: pnpm i
  - name: Install Playwright browsers
    shell: bash
    run: pnpm exec playwright install --with-deps
