services:
  tce-runtime:
    image: "tce-runtime-i"
    container_name: "tce-runtime-c"
    build:
      dockerfile: ".codesandbox/Dockerfile"
      context: "."
    # Witin docker network
    expose:
      - "8010"
      - "8020"
      - "8030"
      - "8080"
    # Witin host
    ports:
      - "8010:8010"
      - "8020:8020"
      - "8030:8030"
      - "8080:8080"
